services:
  # Backend Service
  - type: web
    name: form-generator-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: supabase
          property: connectionString
      - key: DIRECT_URL
        fromDatabase:
          name: supabase
          property: connectionString

  # Frontend Service
  - type: web
    name: form-generator-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: VITE_API_URL
        value: https://form-generator-backend.onrender.com

databases:
  - name: supabase
    plan: free
